### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by HonestyBrave** [Lxrd-AJ/YOLO_V1#4]
hi Lxrd-AJ:
    I run your code, but when one epoch will end, its output error as below
my torch version is: 1.6.0

Traceback (most recent call last):
  File "xxxx/python-code/yolov1/training.py", line 157, in <module>
    predictions = model(images)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "xxxx/python-code/yolov1/yolo_v1.py", line 70, in forward
    linearOutput = self.linear_layers(flattened)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2012, in batch_norm
    _verify_batch_size(input.size())
  File "xxxx/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 1995, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 12544])

**Comment by HonestyBrave** [comment]
hi, Lxrd-AJ:
 i find the solution, i set drop_last=True in the function of "utils.data.DataLoader", but i don't make sure wether is due to two GPU paralle training raise the problem
